# Generated by Django 3.1.3 on 2023-08-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
    ]
